export const RealTimeData = {
  platforms: [
    {
      name: "Netflix",
      brand: "Netflix",
      region: "IN",
      website: "https://www.netflix.com/in/",
      currency: "INR",
      notes:
        "Account for one household; plan differences are quality & screens.",
      plans: [
        {
          id: "mobile",
          display_name: "Mobile",
          price: { amount: 149, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "No ad tier in India." },
          video: { max_resolution: "SD", hdr: [], max_framerate: 30 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: false,
            tv: false,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime; renews monthly.",
          terms_url: "https://help.netflix.com/en/node/24926",
          last_verified: "2025-06-29",
          sources: [
            "https://www.moneycontrol.com/technology/netflix-plans-2025-check-complete-list-benefits-and-which-is-the-right-plan-for-you-article-12992502.html",
            "https://help.netflix.com/en/node/24926",
          ],
        },
        {
          id: "basic",
          display_name: "Basic",
          price: { amount: 199, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime; renews monthly.",
          terms_url: "https://help.netflix.com/en/node/24926",
          last_verified: "2025-06-29",
          sources: [
            "https://www.moneycontrol.com/technology/netflix-plans-2025-check-complete-list-benefits-and-which-is-the-right-plan-for-you-article-12992502.html",
          ],
        },
        {
          id: "standard",
          display_name: "Standard",
          price: { amount: 499, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: {
            max_resolution: "Full HD",
            hdr: ["HDR10", "Dolby Vision"],
            max_framerate: 60,
          },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime; renews monthly.",
          terms_url: "https://help.netflix.com/en/node/24926",
          last_verified: "2025-07-15",
          sources: [
            "https://www.hindustantimes.com/technology/netflix-may-get-pricey-in-2025-4-tricks-to-cut-costs-on-subscription-101752572558106.html",
          ],
        },
        {
          id: "premium",
          display_name: "Premium",
          price: { amount: 649, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: {
            max_resolution: "4K",
            hdr: ["HDR10", "Dolby Vision"],
            max_framerate: 60,
          },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 4, download_devices: 6 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime; renews monthly.",
          terms_url: "https://help.netflix.com/en/node/24926",
          last_verified: "2025-07-15",
          sources: [
            "https://www.hindustantimes.com/technology/netflix-may-get-pricey-in-2025-4-tricks-to-cut-costs-on-subscription-101752572558106.html",
            "https://help.netflix.com/en/node/24926",
          ],
        },
      ],
    },
    {
      name: "Amazon Prime Video",
      brand: "Prime Video",
      region: "IN",
      website: "https://www.primevideo.com/",
      currency: "INR",
      notes:
        "Prime membership includes Prime Video with limited ads since 2025-06-17; ad-free requires add-on.",
      plans: [
        {
          id: "prime-annual",
          display_name: "Amazon Prime (Annual)",
          price: { amount: 1499, billing_period: "year", tax_included: true },
          ads: {
            ad_free: false,
            notes: "Limited ads on movies/shows from 2025-06-17.",
          },
          video: {
            max_resolution: "4K",
            hdr: ["HDR10", "Dolby Vision"],
            max_framerate: 60,
          },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 3, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 6,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [
            {
              id: "ad-free-add-on",
              display_name: "Prime Video Ad-Free",
              price: { amount: 129, billing_period: "month" },
              notes:
                "₹999/year option available; MX Player content may still contain ads.",
            },
          ],
          cancellation: "Cancel anytime; pro-rated refund policy available.",
          terms_url: "https://www.amazon.in/gp/help/customer/display.html",
          last_verified: "2025-06-17",
          sources: [
            "https://economictimes.indiatimes.com/industry/media/entertainment/prime-video-to-introduce-limited-ads-in-india-from-june-17/articleshow/121156978.cms",
            "https://indiatimes.com/trending/amazon-prime-video-to-roll-out-ads-from-june-17-what-the-subscription-changes-mean-for-you-658801.html",
          ],
        },
        {
          id: "prime-monthly",
          display_name: "Amazon Prime (Monthly)",
          price: { amount: 299, billing_period: "month", tax_included: true },
          ads: {
            ad_free: false,
            notes: "Requires ad-free add-on to remove ads.",
          },
          video: {
            max_resolution: "4K",
            hdr: ["HDR10", "Dolby Vision"],
            max_framerate: 60,
          },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 3, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 6,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [
            {
              id: "ad-free-add-on",
              display_name: "Prime Video Ad-Free",
              price: { amount: 129, billing_period: "month" },
              notes: "Optional; removes most ads.",
            },
          ],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.amazon.in/gp/help/customer/display.html",
          last_verified: "2025-06-17",
          sources: [
            "https://economictimes.indiatimes.com/industry/media/entertainment/prime-video-to-introduce-limited-ads-in-india-from-june-17/articleshow/121156978.cms",
            "https://desidime.com/news/prime-video-ad-free-plan-price-launch-now-pay-for-ads-free",
          ],
        },
      ],
    },
    {
      name: "JioHotstar",
      brand: "JioHotstar",
      region: "IN",
      website: "https://www.hotstar.com/in/",
      currency: "INR",
      notes:
        "Disney+ Hotstar India merged with JioCinema in Feb 2025 to form JioHotstar.",
      plans: [
        {
          id: "super-quarterly",
          display_name: "Super (3 months)",
          price: { amount: 299, billing_period: "3-month", tax_included: true },
          ads: {
            ad_free: false,
            notes: "Ads present; sports typically have ads across tiers.",
          },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url:
            "https://help.hotstar.com/in/en/support/solutions/articles/68000001237-disney%2B-hotstar-subscription-plans",
          last_verified: "2025-02-16",
          sources: [
            "https://timesofindia.indiatimes.com/technology/tech-news/jiohotstar-subscription-plans-explained-pricing-features-and-all-other-details/articleshow/118241839.cms",
            "https://en.wikipedia.org/wiki/Disney%2B_Hotstar",
          ],
        },
        {
          id: "premium-monthly",
          display_name: "Premium (Monthly)",
          price: { amount: 299, billing_period: "month", tax_included: true },
          ads: {
            ad_free: true,
            notes: "Movies & shows ad-free; live sports may carry ads.",
          },
          video: {
            max_resolution: "4K",
            hdr: ["HDR10", "Dolby Vision"],
            max_framerate: 60,
          },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 4, download_devices: 4 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url:
            "https://help.hotstar.com/in/en/support/solutions/articles/68000001237-disney%2B-hotstar-subscription-plans",
          last_verified: "2025-08-20",
          sources: [
            "https://www.cashify.in/disney-hotstar-subscription-plans-offers-benefits",
            "https://timesofindia.indiatimes.com/technology/tech-news/jiohotstar-subscription-plans-explained-pricing-features-and-all-other-details/articleshow/118241839.cms",
          ],
        },
      ],
    },
    {
      name: "JioCinema",
      brand: "JioCinema Premium",
      region: "IN",
      website: "https://www.jiocinema.com/",
      currency: "INR",
      notes:
        "Standalone JioCinema Premium plans continue; family plan supports 4 screens.",
      plans: [
        {
          id: "premium-monthly",
          display_name: "Premium Monthly",
          price: { amount: 29, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "Live sports may include ads." },
          video: { max_resolution: "4K", hdr: ["HDR10"], max_framerate: 60 },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.jiocinema.com/terms-and-conditions",
          last_verified: "2025-02-10",
          sources: [
            "https://en.wikipedia.org/wiki/JioCinema",
            "https://www.cashify.in/jio-cinema-premium-plans-pricing-all-details",
          ],
        },
        {
          id: "family-monthly",
          display_name: "Premium Family Monthly",
          price: { amount: 89, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "Live sports may include ads." },
          video: { max_resolution: "4K", hdr: ["HDR10"], max_framerate: 60 },
          audio: { surround: ["5.1", "Dolby Atmos"] },
          concurrency: { simultaneous_streams: 4, download_devices: 4 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.jiocinema.com/terms-and-conditions",
          last_verified: "2025-02-10",
          sources: [
            "https://www.cashify.in/jio-cinema-premium-plans-pricing-all-details",
            "https://indianexpress.com/article/technology/techook/jiocinema-premium-subscription-cost-benefits-shows-9669101/",
          ],
        },
      ],
    },
    {
      name: "SonyLIV",
      brand: "SonyLIV",
      region: "IN",
      website: "https://www.sonyliv.com/subscription",
      currency: "INR",
      notes: "Mobile-only and Premium tiers.",
      plans: [
        {
          id: "mobile-yearly",
          display_name: "Mobile Only (Yearly)",
          price: { amount: 699, billing_period: "year", tax_included: true },
          ads: {
            ad_free: "partial",
            notes:
              "Limited ads may appear; sports often excluded from ad-free.",
          },
          video: { max_resolution: "HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: false,
            tv: false,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://help.sonyliv.com/",
          last_verified: "2025-01-10",
          sources: [
            "https://help.sonyliv.com/top-articles/what-are-the-types-of-subscription-available-on-liv-how-much-does-sony-liv-cost-1",
            "https://www.filmibeat.com/sony-liv-subscription-price-plans-24",
          ],
        },
        {
          id: "premium-monthly",
          display_name: "LIV Premium (Monthly)",
          price: { amount: 399, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "Live sports may contain ads." },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://help.sonyliv.com/",
          last_verified: "2025-01-10",
          sources: [
            "https://help.sonyliv.com/top-articles/what-are-the-types-of-subscription-available-on-liv-how-much-does-sony-liv-cost-1",
          ],
        },
        {
          id: "premium-yearly",
          display_name: "LIV Premium (Yearly)",
          price: { amount: 1499, billing_period: "year", tax_included: true },
          ads: { ad_free: true, notes: "Live sports may contain ads." },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://help.sonyliv.com/",
          last_verified: "2025-01-10",
          sources: [
            "https://help.sonyliv.com/top-articles/what-are-the-types-of-subscription-available-on-liv-how-much-does-sony-liv-cost-1",
            "https://www.filmibeat.com/sony-liv-subscription-price-plans-24",
          ],
        },
      ],
    },
    {
      name: "ZEE5",
      brand: "ZEE5",
      region: "IN",
      website: "https://www.zee5.com/",
      currency: "INR",
      notes: "Regional packs exist; pricing and device limits vary by pack.",
      plans: [
        {
          id: "regional-combos",
          display_name: "Regional Packs (example: Hindi/Punjabi/Bhojpuri)",
          price: { amount: 199, billing_period: "month", tax_included: true },
          ads: {
            ad_free: "partial",
            notes: "Documentation lists 'With Ads' for certain packs.",
          },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: ["Dolby Atmos"] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url:
            "https://helpcenter.zee5.com/portal/en/kb/articles/premium-subscription-plans-12-5-2023",
          last_verified: "2025-01-18",
          sources: [
            "https://helpcenter.zee5.com/portal/en/kb/articles/premium-subscription-plans-12-5-2023",
            "https://www.gadgets360.com/entertainment/features/zee5-subscription-plans-7435864",
          ],
        },
      ],
    },
    {
      name: "Lionsgate Play",
      brand: "Lionsgate Play",
      region: "IN",
      website: "https://www.lionsgateplay.com/",
      currency: "INR",
      notes: "Hollywood & international TV; often bundled via channels.",
      plans: [
        {
          id: "quarterly",
          display_name: "Quarterly",
          price: { amount: 399, billing_period: "3-month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 5, download_devices: 5 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.lionsgateplay.com/terms",
          last_verified: "2024-10-17",
          sources: [
            "https://www.gadgets360.com/entertainment/news/lionsgate-play-free-streaming-india-gatecrash-promotion-seven-days-october-6808947",
            "https://www.filmibeat.com/lionsgate-play-subscription-price-plans-63",
          ],
        },
        {
          id: "annual",
          display_name: "Annual",
          price: { amount: 699, billing_period: "year", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: ["5.1"] },
          concurrency: { simultaneous_streams: 5, download_devices: 5 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.lionsgateplay.com/terms",
          last_verified: "2024-10-17",
          sources: [
            "https://www.gadgets360.com/entertainment/news/lionsgate-play-free-streaming-india-gatecrash-promotion-seven-days-october-6808947",
            "https://www.filmibeat.com/lionsgate-play-subscription-price-plans-63",
          ],
        },
      ],
    },
    {
      name: "Hoichoi",
      brand: "Hoichoi",
      region: "IN",
      website: "https://www.hoichoi.tv/",
      currency: "INR",
      notes: "Bengali-first service; two tiers common in India.",
      plans: [
        {
          id: "quarterly",
          display_name: "Quarterly",
          price: { amount: 499, billing_period: "3-month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 4, download_devices: 4 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://support.hoichoi.tv/",
          last_verified: "2025-03-19",
          sources: [
            "https://support.hoichoi.tv/support/solutions/articles/35000132720-what-subscription-plans-does-hoichoi-offer-",
          ],
        },
        {
          id: "annual",
          display_name: "Annual",
          price: { amount: 999, billing_period: "year", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://support.hoichoi.tv/",
          last_verified: "2025-03-19",
          sources: [
            "https://support.hoichoi.tv/support/solutions/articles/35000132720-what-subscription-plans-does-hoichoi-offer-",
          ],
        },
      ],
    },
    {
      name: "Sun NXT",
      brand: "Sun NXT",
      region: "IN",
      website: "https://www.sunnxt.com/",
      currency: "INR",
      notes: "South-first catalog (Tamil/Telugu/Malayalam/Kannada).",
      plans: [
        {
          id: "basic-annual",
          display_name: "Basic (Annual)",
          price: { amount: 579, billing_period: "year", tax_included: true },
          ads: {
            ad_free: false,
            notes: "Ads present; no offline downloads or casting.",
          },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 0 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: false,
            console: false,
          },
          profiles: 5,
          downloads: false,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.sunnxt.com/faq",
          last_verified: "2025-03-07",
          sources: [
            "https://www.grabon.in/indulge/our-picks/sun-nxt-subscription-plans-cost/",
            "https://www.sunnxt.com/faq",
          ],
        },
        {
          id: "premium-annual",
          display_name: "Premium (Annual)",
          price: { amount: 899, billing_period: "year", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 4, download_devices: 4 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.sunnxt.com/faq",
          last_verified: "2025-03-07",
          sources: [
            "https://www.grabon.in/indulge/our-picks/sun-nxt-subscription-plans-cost/",
            "https://www.sunnxt.com/faq",
          ],
        },
      ],
    },
    {
      name: "aha",
      brand: "aha",
      region: "IN",
      website: "https://www.aha.video/",
      currency: "INR",
      notes: "Telugu & Tamil originals; frequent promos.",
      plans: [
        {
          id: "pocket-pack-monthly",
          display_name: "Pocket Pack (Monthly)",
          price: { amount: 67, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "Full HD", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 1 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: false,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.aha.video/terms",
          last_verified: "2025-03-31",
          sources: [
            "https://www.medianews4u.com/aha-brings-affordable-streaming-with-pocket-pack-for-just-%E2%82%B967/",
          ],
        },
        {
          id: "gold-annual",
          display_name: "Gold (Annual)",
          price: { amount: 1499, billing_period: "year", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: ["Dolby Atmos"] },
          concurrency: { simultaneous_streams: 2, download_devices: 2 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 5,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.aha.video/terms",
          last_verified: "2025-05-01",
          sources: [
            "https://www.filmibeat.com/aha-video-subscription-price-plans-3",
            "https://www.aha.video/subscription/viewplans",
          ],
        },
      ],
    },
    {
      name: "Apple TV+",
      brand: "Apple TV+",
      region: "IN",
      website: "https://www.apple.com/in/apple-tv-plus/",
      currency: "INR",
      notes: "Apple One bundles available; student Music includes TV+.",
      plans: [
        {
          id: "monthly",
          display_name: "Monthly",
          price: { amount: 99, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: {
            max_resolution: "4K",
            hdr: ["Dolby Vision", "HDR10"],
            max_framerate: 60,
          },
          audio: { surround: ["Dolby Atmos"] },
          concurrency: { simultaneous_streams: 6, download_devices: 6 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: false,
          },
          profiles: 6,
          downloads: true,
          bundles: [
            {
              name: "Apple One (Individual)",
              price_override: null,
              notes: "Starts ₹195/mo.",
            },
          ],
          eligibility: { student: true, family: true },
          trial: { free_days: 7 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url:
            "https://www.apple.com/legal/internet-services/itunes/in/terms.html",
          last_verified: "2025-08-15",
          sources: [
            "https://www.apple.com/in/apple-tv-plus/",
            "https://tv.apple.com/in",
          ],
        },
      ],
    },
    {
      name: "YouTube Premium",
      brand: "YouTube",
      region: "IN",
      website: "https://www.youtube.com/premium",
      currency: "INR",
      notes:
        "Video + Music; not a traditional OTT but often compared in pricing.",
      plans: [
        {
          id: "individual-monthly",
          display_name: "Individual (Monthly)",
          price: { amount: 149, billing_period: "month", tax_included: true },
          ads: {
            ad_free: true,
            notes: "Ad-free YouTube + background play & downloads.",
          },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 1, download_devices: 10 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 1,
          downloads: true,
          eligibility: { student: true, family: true },
          trial: { free_days: 30 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.youtube.com/t/terms_paidservice",
          last_verified: "2025-05-06",
          sources: [
            "https://www.youtube.com/premium",
            "https://www.theverge.com/news/661462/youtube-premium-two-people-plan",
          ],
        },
        {
          id: "duo-experiment",
          display_name: "Premium for Two (Pilot)",
          price: { amount: 219, billing_period: "month", tax_included: true },
          ads: {
            ad_free: true,
            notes: "Pilot in India; availability may vary.",
          },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 2, download_devices: 10 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 2,
          downloads: true,
          eligibility: { student: false, family: false },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.youtube.com/t/terms_paidservice",
          last_verified: "2025-05-06",
          sources: [
            "https://www.theverge.com/news/661462/youtube-premium-two-people-plan",
            "https://www.indiatoday.in/technology/news/story/youtube-is-testing-combo-premium-plan-for-two-in-india-price-to-start-at-rs-219-2720295-2025-05-06",
          ],
        },
        {
          id: "family-monthly",
          display_name: "Family (Monthly)",
          price: { amount: 299, billing_period: "month", tax_included: true },
          ads: { ad_free: true, notes: "" },
          video: { max_resolution: "4K", hdr: [], max_framerate: 60 },
          audio: { surround: [] },
          concurrency: { simultaneous_streams: 6, download_devices: 10 },
          device_support: {
            mobile: true,
            tablet: true,
            web: true,
            tv: true,
            console: true,
          },
          profiles: 6,
          downloads: true,
          eligibility: { student: false, family: true },
          trial: { free_days: 0 },
          add_ons: [],
          cancellation: "Cancel anytime.",
          terms_url: "https://www.youtube.com/t/terms_paidservice",
          last_verified: "2025-05-06",
          sources: [
            "https://www.theverge.com/news/661462/youtube-premium-two-people-plan",
            "https://www.youtube.com/premium",
          ],
        },
      ],
    },
  ],
};
